spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:auto: validate
        jdbc:
          batch_size: 10
          fetch_size: 10
  liquibase:
    enabled: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: iso
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 352025992724-p1q7vq8odtf2r1apqcdq408ou3c7nsbr.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: openid,email,profile

springdoc:
  swagger-ui:
    enabled: true
    oauth:
      client-id: 352025992724-p1q7vq8odtf2r1apqcdq408ou3c7nsbr.apps.googleusercontent.com
      client-secret: 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
      scopes: openid,email,profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html

logging:
  level:
    root: info
    com.example.spring.database.utils.ConnectionPool: warn
    org.springframework.jdbc.core: TRACE
  file:
    #    path: ./log/log/
    name: ./log/spring-example.log


db:
  username: postgres
  password: postgres
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 567
    third: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

